### ISSUE TITLE
Issue folder structure with awesome fonts (ember-cli 2.13.1)

### ISSUE THREAD

**Issue by jagroeneveld** [MyPureCloud/fixtable-ember#100]
After installing with 'ember install fixtable-ember' and running 'ember s' I get the following error:
(awesome-font is installed in '/home/<username>/ember-quickstart/node_modules/font-awesome/fonts'

ENOENT: no such file or directory, scandir '/home/<username>/ember-quickstart/node_modules/fixtable-ember/node_modules/font-awesome/fonts'
Error: ENOENT: no such file or directory, scandir '/home/<username>/ember-quickstart/node_modules/fixtable-ember/node_modules/font-awesome/fonts'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Class.included (/home/<username>/ember-quickstart/node_modules/fixtable-ember/index.js:20:34)
    at Class.superWrapper [as included] (/home/<username>/ember-quickstart/node_modules/core-object/lib/assign-properties.js:34:20)
    at EmberApp.<anonymous> (/home/<username>/ember-quickstart/node_modules/ember-cli/lib/broccoli/ember-app.js:517:17)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/home/<username>/ember-quickstart/node_modules/ember-cli/lib/broccoli/ember-app.js:512:47)
    at new EmberApp (/home/<username>/ember-quickstart/node_modules/ember-cli/lib/broccoli/ember-app.js:142:10)
    at module.exports (/home/<username>/ember-quickstart/ember-cli-build.js:5:13)
    at Builder.setupBroccoliBuilder (/home/<username>/ember-quickstart/node_mod

**Comment by smargovsky** [comment]
@jagroeneveld Can you give more details, please?  Is this in an app, addon, or engine?  Did you move `fixtable-ember` into `dependencies` from `devDependencies` ( where `ember install` puts it by default )?  

Usually when we see this it is due to a dependency version mismatch somewhere in the tree.  Can you eliminate this as a cause?

Thank you!

**Comment by jagroeneveld** [comment]
Hi Serge,


Thanks voor your efforts. Your comment resolved the situation for me. Here is a recollection of what I did.


What I did is:

  1.  I created a project ember-quickstart
  2.  I installed fixtable with : "ember install fixtable-ember
  3.  I started "ember s"

After which I get the errors I mentioned. I did it again today and got:


ENOENT: no such file or directory, scandir '/home/jgroeneveld/ember-quickstart/node_modules/fixtable-ember/node_modules/font-awesome/fonts'

Error: ENOENT: no such file or directory, scandir '/home/jgroeneveld/ember-quickstart/node_modules/fixtable-ember/node_modules/font-awesome/fonts'

    at Error (native)

    at Object.fs.readdirSync (fs.js:952:18)

    at Class.included (/home/jgroeneveld/ember-quickstart/node_modules/fixtable-ember/index.js:20:34)

    at Class.superWrapper [as included] (/home/jgroeneveld/ember-quickstart/node_modules/core-object/lib/assign-properties.js:34:20)

    at EmberApp.<anonymous> (/home/jgroeneveld/ember-quickstart/node_modules/ember-cli/lib/broccoli/ember-app.js:517:17)

    at Array.filter (native)

    at EmberApp._notifyAddonIncluded (/home/jgroeneveld/ember-quickstart/node_modules/ember-cli/lib/broccoli/ember-app.js:512:47)

    at new EmberApp (/home/jgroeneveld/ember-quickstart/node_modules/ember-cli/lib/broccoli/ember-app.js:142:10)

    at module.exports (/home/jgroeneveld/ember-quickstart/ember-cli-build.js:5:13)

    at Builder.setupBroccoliBuilder (/home/jgroeneveld/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:56:19)

I edited "package.json" and added (just before the existing devDependencies section):

"Dependencies": {

    "fixtable-ember": "^3.0.3"

  },

This helped indeed.

Kind regards, Jan


________________________________
