### ISSUE TITLE
Broccoli plugin error on ember-cli v2.13.x

### ISSUE THREAD

**Issue by dipeshpp** [MyPureCloud/fixtable-ember#97]
I get the following error when I try to launch my app. Any ideas how to fix it?

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open 'C:\workspace\ProjectName\tmp\source_map_concat-input_base_path-SjMvR1OV.tmp\C:\workspace\ProjectName\node_modules\fixtable-ember\node_modules\fixtable\dist\fixtable.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at SourceMap.addFile (C:\workspace\ProjectName\node_modules\fast-sourcemap-concat\lib\source-map.js:75:31)
    at C:\workspace\ProjectName\node_modules\broccoli-concat\concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (C:\workspace\ProjectName\node_modules\broccoli-concat\concat.js:198:24)
    at C:\workspace\ProjectName\node_modules\fast-sourcemap-concat\lib\source-map.js:393:12
    at initializePromise (C:\workspace\ProjectName\node_modules\rsvp\dist\rsvp.js:589:5)
    at new Promise$1 (C:\workspace\ProjectName\node_modules\rsvp\dist\rsvp.js:1077:33)

The broccoli plugin was instantiated at: 
    at Concat.Plugin (C:\workspace\ProjectName\node_modules\broccoli-plugin\index.js:7:31)
    at new Concat (C:\workspace\ProjectName\node_modules\broccoli-concat\concat.js:38:10)
    at module.exports (C:\workspace\ProjectName\node_modules\broccoli-concat\index.js:26:10)
    at EmberApp._concatFiles (C:\workspace\ProjectName\node_modules\ember-cli\lib\broccoli\ember-app.js:432:12)
    at EmberApp.javascript (C:\workspace\ProjectName\node_modules\ember-cli\lib\broccoli\ember-app.js:1275:14)
    at EmberApp.toArray (C:\workspace\ProjectName\node_modules\ember-cli\lib\broccoli\ember-app.js:1662:12)
    at EmberApp.toTree (C:\workspace\ProjectName\node_modules\ember-cli\lib\broccoli\ember-app.js:1684:38)
    at module.exports (C:\workspace\ProjectName\ember-cli-build.js:27:14)
    at Builder.setupBroccoliBuilder (C:\workspace\ProjectName\node_modules\ember-cli\lib\models\builder.js:56:19)
    at new Builder (C:\workspace\ProjectName\node_modules\ember-cli\lib\models\builder.js:30:10)
```

**Comment by smargovsky** [comment]
@dipeshpp Not sure this is necessarily a problem w/ `fixtable-ember`.  Can you provide more details on how to reproduce this?

**Comment by dipeshpp** [comment]
Nevermind, this was only reproducible on Windows. It works fine on Linux.
